[workspace]
members = [
    "onemfive_common",
    "onemfive_platform",
    "onemfive_cli",
    "onemfive_desktop",
    "onemfive_mobile"
]

[profile.dev]
opt-level = 0
debug = 2

[profile.test]
opt-level = 0
debug = 1

[profile.release]
opt-level = 3
debug = 0