[workspace]
members = [
    "platform",
    "cli",
    "desktop",
    "mobile"
]

[profile.dev]
opt-level = 0
debug = 2

[profile.test]
opt-level = 0
debug = 1

[profile.release]
opt-level = 3
debug = 0