[workspace]
members = [
    "1m5_common",
    "1m5_platform",
    "1m5_cli",
    "1m5_desktop",
    "1m5_mobile"
]

[profile.dev]
opt-level = 0
debug = 2

[profile.test]
opt-level = 0
debug = 1

[profile.release]
opt-level = 3
debug = 0